/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as HomeRouteImport } from './routes/home'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ActivitiesLogRouteImport } from './routes/activities.log'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssessmentsRouteImport } from './routes/admin.assessments'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as OnboardingAssessmentRouteImport } from './routes/onboarding.assessment'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileWellbeingRouteImport } from './routes/profile.wellbeing'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsIdRouteImport } from './routes/programs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesLogRoute = ActivitiesLogRouteImport.update({
  id: '/activities/log',
  path: '/activities/log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/admin/assessments',
  path: '/admin/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAssessmentRoute = OnboardingAssessmentRouteImport.update({
  id: '/onboarding/assessment',
  path: '/onboarding/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWellbeingRoute = ProfileWellbeingRouteImport.update({
  id: '/profile/wellbeing',
  path: '/profile/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/activities/log': typeof ActivitiesLogRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/onboarding/assessment': typeof OnboardingAssessmentRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/profile/wellbeing': typeof ProfileWellbeingRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/activities/log': typeof ActivitiesLogRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/onboarding/assessment': typeof OnboardingAssessmentRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/profile/wellbeing': typeof ProfileWellbeingRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/activities/log': typeof ActivitiesLogRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/onboarding/assessment': typeof OnboardingAssessmentRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/profile/wellbeing': typeof ProfileWellbeingRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/check-in'
    | '/home'
    | '/journey'
    | '/activities/log'
    | '/admin/assessments'
    | '/admin/attendance'
    | '/admin/participants'
    | '/admin/reports'
    | '/onboarding/assessment'
    | '/onboarding/profile'
    | '/profile/wellbeing'
    | '/programs/$id'
    | '/admin/'
    | '/profile/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/check-in'
    | '/home'
    | '/journey'
    | '/activities/log'
    | '/admin/assessments'
    | '/admin/attendance'
    | '/admin/participants'
    | '/admin/reports'
    | '/onboarding/assessment'
    | '/onboarding/profile'
    | '/profile/wellbeing'
    | '/programs/$id'
    | '/admin'
    | '/profile'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/check-in'
    | '/home'
    | '/journey'
    | '/activities/log'
    | '/admin/assessments'
    | '/admin/attendance'
    | '/admin/participants'
    | '/admin/reports'
    | '/onboarding/assessment'
    | '/onboarding/profile'
    | '/profile/wellbeing'
    | '/programs/$id'
    | '/admin/'
    | '/profile/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckInRoute: typeof CheckInRoute
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRoute
  ActivitiesLogRoute: typeof ActivitiesLogRoute
  AdminAssessmentsRoute: typeof AdminAssessmentsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  OnboardingAssessmentRoute: typeof OnboardingAssessmentRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  ProfileWellbeingRoute: typeof ProfileWellbeingRoute
  ProgramsIdRoute: typeof ProgramsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/log': {
      id: '/activities/log'
      path: '/activities/log'
      fullPath: '/activities/log'
      preLoaderRoute: typeof ActivitiesLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/admin/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/assessment': {
      id: '/onboarding/assessment'
      path: '/onboarding/assessment'
      fullPath: '/onboarding/assessment'
      preLoaderRoute: typeof OnboardingAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/wellbeing': {
      id: '/profile/wellbeing'
      path: '/profile/wellbeing'
      fullPath: '/profile/wellbeing'
      preLoaderRoute: typeof ProfileWellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id': {
      id: '/programs/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckInRoute: CheckInRoute,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRoute,
  ActivitiesLogRoute: ActivitiesLogRoute,
  AdminAssessmentsRoute: AdminAssessmentsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminReportsRoute: AdminReportsRoute,
  OnboardingAssessmentRoute: OnboardingAssessmentRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  ProfileWellbeingRoute: ProfileWellbeingRoute,
  ProgramsIdRoute: ProgramsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
